trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  blazorProject: '.'           # Root of your Blazor project
  consoleAppPath: './Tools/ExportToJson'  # Path to SQLite ? JSON exporter
  outputLocation: 'wwwroot'    # Static web app output folder

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'  # Match your project's SDK version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore
  displayName: 'Restore Dependencies'

- script: |
    dotnet build $(consoleAppPath) --configuration $(buildConfiguration)
    dotnet run --project $(consoleAppPath)
  displayName: 'Run SQLite ? JSON Exporter'

- script: |
    dotnet build $(blazorProject) --configuration $(buildConfiguration)
    dotnet publish $(blazorProject) -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/app
  displayName: 'Build Blazor WebAssembly App'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '$(Build.ArtifactStagingDirectory)/app'
    output_location: ''
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
    is_static_export: true
  displayName: 'Deploy to Azure Static Web App'
