trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
    # Define variables for the build configuration and project paths
    - name: buildConfiguration
      value: 'Release'
    - name: blazorAppPath
      value: 'ResumeSite/ResumeSite/ResumeSite.Web.csproj'
    - name: consoleAppPath
      value: 'ResumeSite/ResumeSite.Export/ResumeSite.Export.csproj'
    - name: outputLocation
      value: 'wwwroot'
    - group: Deployment 

steps:

    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    
#    - task: DotNetCoreCLI@2
#      displayName: 'Build SQLite => JSON Exporter'
#      inputs:
#        command: 'build'
#        projects: '$(consoleAppPath)'

#    - task: DotNetCoreCLI@2
#      displayName: 'Run SQLite => JSON Exporter'
#      inputs:
#        command: 'build'
#        projects: '$(consoleAppPath)'

    - task: DotNetCoreCLI@2
      displayName: 'Build Blazor WebAssembly App'
      inputs:
        command: 'build'
        projects: '$(blazorAppPath)'
        arguments: '--configuration $(buildConfiguration)'
        
    - task: DotNetCoreCLI@2
      displayName: 'Publish Blazor WebAssembly App'
      inputs:
        command: 'publish'
        projects: '$(blazorAppPath)'
        arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/app'
        
    - script: |
        echo "Listing contents of app directory:"
        ls -R $(Build.ArtifactStagingDirectory)/app
      displayName: 'List contents of publish output'
      
    - task: AzureStaticWebApp@0
      inputs:
        app_location: '$(Build.ArtifactStagingDirectory)/app'
        output_location: 'wwwroot'
        azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
        is_static_export: true
      displayName: 'Deploy to Azure Static Web App'

