trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  blazorAppPath: '.'           # Root of your Blazor project
  consoleAppPath: './Tools/ExportToJson'  # Path to SQLite ? JSON exporter
  outputLocation: 'wwwroot'    # Static web app output folder

steps:

    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: 'Build SQLite => JSON Exporter'
      inputs:
        command: 'build'
        arguments: '--project $(consoleAppPath)'

    - task: DotNetCoreCLI@2
      displayName: 'Run SQLite => JSON Exporter'
      inputs:
        command: 'build'
        arguments: '--project $(consoleAppPath)'

    - task: DotNetCoreCLI@2
      displayName: 'Build Blazor WebAssembly App'
      inputs:
        command: 'build'
        arguments: '--project $(blazorAppPath) --configuration $(buildConfiguration)'
        
    - task: DotNetCoreCLI@2
      displayName: 'publis Blazor WebAssembly App'
      inputs:
        command: 'publish'
        arguments: '--project $(blazorAppPath) -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/app'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: '$(Build.ArtifactStagingDirectory)/app'
        output_location: ''
        azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
        is_static_export: true
      displayName: 'Deploy to Azure Static Web App'
